[package]
name = "xonix"
version = "0.1.2"
edition = "2021"
authors = ["Denis Salmanovich"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
macroquad-virtual-joystick = "0.2.0"